apiVersion: v1
kind: Service
metadata:
  name: http-service
  namespace: http-test
spec:
  type: LoadBalancer
  selector:
    app: http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
